name: "Docker build & push"
description: "Docker build & push"

inputs:
  registry:
    description: "Docker registry"
    required: false
    default: ghcr.io/${{ github.repository_owner }}
  name:
    description: "Docker image name"
    required: true
  registry_username:
    description: "Docker registry username"
    required: false
    default: ${{ github.actor }}
  registry_password:
    description: "Docker registry password"
    required: true
  arch:
    description: "Docker image arch"
    required: false
    default: 'linux/amd64'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: name=${{ inputs.registry }}/${{ inputs.name }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ inputs.arch }}

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Build for branch
      id: build-branch
      if: github.ref_type != 'tag'
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: ${{ inputs.arch }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: false

    - name: Build for tag
      id: build-tag
      if: github.ref_type == 'tag'
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: ${{ inputs.arch }}
        labels: ${{ steps.meta.outputs.labels }}
        outputs: type=image,name=${{ inputs.registry }}/${{ inputs.name }},push-by-digest=true,name-canonical=true,push=true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true

    - name: Export digest
      if: github.ref_type == 'tag'
      shell: bash
      run: |
        mkdir -p /tmp/digests
        digest="${{ steps.build-tag.outputs.digest }}"
        touch "/tmp/digests/${digest#sha256:}"      

    - name: Upload digest
      if: github.ref_type == 'tag'
      uses: actions/upload-artifact@v3
      with:
        name: digests
        path: /tmp/digests/*
        if-no-files-found: error
        retention-days: 1